version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    tty: true